// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVrmv1orU_-FLVXPFirEwyiN83ImjoYEQ',
    appId: '1:891576872027:web:f0f5743ac41f777d57237e',
    messagingSenderId: '891576872027',
    projectId: 'warriorpath-89a85',
    authDomain: 'warriorpath-89a85.firebaseapp.com',
    storageBucket: 'warriorpath-89a85.firebasestorage.app',
    measurementId: 'G-R30BDW4RSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-8Uj9ycOFdyk2D3drrKnPa3ps3FHytvY',
    appId: '1:891576872027:android:c0b199ef6daf889757237e',
    messagingSenderId: '891576872027',
    projectId: 'warriorpath-89a85',
    storageBucket: 'warriorpath-89a85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs6GoKFjmhUDCol364okgZ7lO_D_1AKuc',
    appId: '1:891576872027:ios:4fb588ba51f79f8e57237e',
    messagingSenderId: '891576872027',
    projectId: 'warriorpath-89a85',
    storageBucket: 'warriorpath-89a85.firebasestorage.app',
    iosBundleId: 'com.warriorpath.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs6GoKFjmhUDCol364okgZ7lO_D_1AKuc',
    appId: '1:891576872027:ios:cb84410d774a148557237e',
    messagingSenderId: '891576872027',
    projectId: 'warriorpath-89a85',
    storageBucket: 'warriorpath-89a85.firebasestorage.app',
    iosBundleId: 'com.example.matchhouseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVrmv1orU_-FLVXPFirEwyiN83ImjoYEQ',
    appId: '1:891576872027:web:a0f4c38f5f9b0dcc57237e',
    messagingSenderId: '891576872027',
    projectId: 'warriorpath-89a85',
    authDomain: 'warriorpath-89a85.firebaseapp.com',
    storageBucket: 'warriorpath-89a85.firebasestorage.app',
    measurementId: 'G-XGRM6WQ1GN',
  );
}
