// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVrmv1orU_-FLVXPFirEwyiN83ImjoYEQ',
    appId: '1:891576872027:web:f0f5743ac41f777d57237e',
    messagingSenderId: '891576872027',
    projectId: 'toko-113ff',
    authDomain: 'toko-113ff.firebaseapp.com',
    storageBucket: 'toko-113ff.firebasestorage.app',
    measurementId: 'G-R30BDW4RSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC67FXBNnDek7DhhYSQK0df9wctx0l_kM8',
    appId: '1:657051316118:android:e44122bb5ced3c84b6f7b7',
    messagingSenderId: '657051316118',
    projectId: 'toko-113ff',
    storageBucket: 'toko-113ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5HYU6C9OgUJJGYIX0hFefwd38mjIlhjo',
    appId: '1:657051316118:ios:c00b6f9749d34e0fb6f7b7',
    messagingSenderId: '657051316118',
    projectId: 'toko-113ff',
    storageBucket: 'toko-113ff.firebasestorage.app',
    iosBundleId: 'com.toko.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs6GoKFjmhUDCol364okgZ7lO_D_1AKuc',
    appId: '1:891576872027:ios:cb84410d774a148557237e',
    messagingSenderId: '891576872027',
    projectId: 'toko-113ff',
    storageBucket: 'toko-113ff.firebasestorage.app',
    iosBundleId: 'com.example.toko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVrmv1orU_-FLVXPFirEwyiN83ImjoYEQ',
    appId: '1:891576872027:web:a0f4c38f5f9b0dcc57237e',
    messagingSenderId: '891576872027',
    projectId: 'toko-113ff',
    authDomain: 'toko-113ff.firebaseapp.com',
    storageBucket: 'toko-113ff.firebasestorage.app',
    measurementId: 'G-XGRM6WQ1GN',
  );
}